<?php
/** @var $block \Magento\Framework\View\Element\Template */

/** @var \GoMage\Samples\ViewModel\Claim $viewModel */
$viewModel = $block->getData('view_model');
?>

<?php if ($block->hasWrapper()) : ?>
<li class="sample-basket-link-menu">
<?php endif; ?>

<div data-role="basket-link">

    <div class="sample-basket-link-wrap" data-bind="scope: 'basket-link'">
        <span data-bind="click: toggleModal"
              style="cursor: pointer"
              class="sample-basket-link"
              title="<?= $block->escapeHtmlAttr(__('Sample basket')) ?>">
            <span class="sample-basket-icon">
                <svg id="_Laag_" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30.87 30.97"><defs><style>.cls-1{fill:#1d1d1b;}</style></defs><path class="cls-1" d="m1.34,0C.6,0,0,.61,0,1.35v23.23c0,3.53,2.86,6.4,6.38,6.4h23.15c.74,0,1.34-.61,1.34-1.35v-10.1c0-.74-.6-1.35-1.34-1.35h-7.75l5.48-5.5c.25-.26.39-.59.39-.95s-.14-.7-.39-.96l-7.12-7.14c-.51-.51-1.39-.51-1.9,0l-5.49,5.5V1.35c0-.74-.6-1.35-1.34-1.35H1.34Zm27.85,29.29H10.7l9.39-9.42h9.1v9.42Zm-22.81,0c-2.59,0-4.7-2.11-4.7-4.71v-6.73h9.39v6.73c0,1.27-.5,2.46-1.41,3.36-.26.25-.55.47-.88.67-.05.03-.1.06-.16.09-.38.2-.72.34-1.06.43-.43.11-.81.17-1.18.17Zm0-5.9c-.65,0-1.18.53-1.18,1.19s.53,1.18,1.18,1.18,1.18-.53,1.18-1.18-.53-1.19-1.18-1.19Zm6.38,1.45v-13.32l6.44-6.46,6.64,6.66-13.08,13.12Zm-1.68-8.68H1.68v-6.39h9.39v6.39Zm0-8.08H1.68V1.69h9.39v6.39Z"/></svg>
            </span>
            <i class="fal fa-swatchbook"></i>
            <span class="text"><?= $block->escapeHtml(__('samples')) ?></span>
            <!-- ko if: items().length -->
            <span class="counter qty" data-role="sample-counter" style="display: none">
                <span class="counter-number">
                    <!-- ko text: items().length --><!-- /ko -->
                </span>
            </span>
            <!-- /ko -->
            <!-- ko ifnot: items().length -->
            <span class="counter qty" data-role="sample-counter">
                <span class="counter-number">0</span>
            </span>
            <!-- /ko -->
        </span>
    </div>

</div>

<script type="text/x-magento-init">
{
    "[data-role=basket-link]": {
        "Magento_Ui/js/core/app": {
            "components": {
                "basket-link": {
                    "component": "GoMage_Samples/js/view/basket/link",
                    "selectors": {
                        "modal": "[data-role=sample-modal]",
                        "counter": "[data-role=sample-counter]"
                    }
                }
            }
        }
    }
}
</script>

<?php if ($block->hasWrapper()) : ?>
</li>
<?php endif; ?>

