<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div class="product-info-messages">
    <div class="discount-message" data-role="product-info-discount-message" style="display:none;">
        <?= $block->escapeHtml($block->getData('discount_message')) ?>
    </div>
    <div class="delivery-message">&nbsp;</div>
    <div class="measurement-message">
        <?= $block->escapeHtml($block->getData('measurement_message')) ?>
    </div>
</div>
