<?php
/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox $block */

/** @var \Magento\Framework\Pricing\Price\PriceInterface $smartblindsPriceModel */
$finalPriceModel = $block->getPriceType('final_price');

$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<span class="normal-price" data-role="smartblinds-price" style="display:none;">
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
        'display_label' => __('from price'),
        'price_id' => $block->getPriceId('product-price-' . $idSuffix),
        'price_type' => 'finalPrice',
        'include_container' => true,
        'schema' => $schema,
    ]);
    ?>
</span>
