<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
$_post = $block->getPost();
$_postUrl = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null);
?>
<div class="post-view">
    <div class="post-holder post-holder-<?= (int)$_post->getId() ?>">
        <div class="post-content">
            <?php if ($_categoriesCount = $_post->getCategoriesCount()): ?>
                <div class="category-name-list mobile-block">
                    <?php $n = 0; ?>
                    <?php foreach ($_post->getParentCategories() as $ct) { ?>
                        <?php $n++; ?>
                        <a title="<?= $block->escapeHtml($ct->getTitle()) ?>"
                           href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>"
                        ><?= $block->escapeHtml($ct->getTitle()) ?></a><?= /*@noEscape*/ ($n != $_categoriesCount) ? ',' : '' ?>
                    <?php } ?>
                </div>
            <?php endif; ?>
            <div class="post-main-image">
                <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                    <?php
                    $featuredImgAlt = $_post->getData('featured_img_alt');
                    if (!$featuredImgAlt) {
                        $featuredImgAlt = $_postName;
                    }
                    ?>
                    <img src="<?= $block->escapeUrl($featuredImage) ?>"
                         alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                <?php } ?>
            </div>
            <?php if ($_categoriesCount = $_post->getCategoriesCount()): ?>
                <div class="category-name-list desktop-block">
                    <?php $n = 0; ?>
                    <?php foreach ($_post->getParentCategories() as $ct) { ?>
                        <?php $n++; ?>
                        <a title="<?= $block->escapeHtml($ct->getTitle()) ?>"
                           href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>"
                        ><?= $block->escapeHtml($ct->getTitle()) ?></a><?= /*@noEscape*/ ($n != $_categoriesCount) ? ',' : '' ?>
                    <?php } ?>
                </div>
            <?php endif; ?>
            <div class="post-description clearfix">
                <div class="post-text-hld">
                    <?= /*@noEscape*/ $block->getContent() ?>
                    <div class="clear clearfix"></div>
                </div>
            </div>
        </div>

        <div class="post-bottom">
            <?= $block->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>
