<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = \Magento\Framework\App\ObjectManager::getInstance()
                    ->get(\Magento\Framework\App\Config\ScopeConfigInterface::class)
                    ->getValue('smartblinds_configurable_product/settings/add_to_cart_text', \Magento\Store\Model\ScopeInterface::SCOPE_STORE) ?: __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart a2"
                        id="product-addtocart-button"
                        style="display: none"
                        disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                 <p style="margin-top: 10px; z-index: 50 ">
                 <?php
                echo $productText = \Magento\Framework\App\ObjectManager::getInstance()
                    ->get(\Magento\Framework\App\Config\ScopeConfigInterface::class)
                    ->getValue('smartblinds_configurable_product/pages/producttext', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
                ?></p>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        },
        "*": {
            "Smartblinds_ConfigurableProduct/js/view/progress": {}
        }
    }
</script>
