<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<script>
require([
    "jquery",
    'Magento_Ui/js/modal/alert',
    'Magento_Ui/js/modal/prompt',
    "collapsable",
    "prototype"
], function(jQuery, alert, prompt){

    function toggleApplyVisibility(select) {
        if ($(select).value == 1) {
            $(select).next('select').removeClassName('no-display');
            $(select).next('select').removeClassName('ignore-validate');

        } else {
            $(select).next('select').addClassName('no-display');
            $(select).next('select').addClassName('ignore-validate');
            var options = $(select).next('select').options;
            for( var i=0; i < options.length; i++) {
                options[i].selected = false;
            }
        }
    }

    function checkOptionsPanelVisibility(){
        if($('manage-options-panel')){
            var panel = $('manage-options-panel').up('.fieldset');

            if($('input_type')
            ){
                panel.show();
            }
            else {
                panel.hide();
            }
        }
    }

    function bindAttributeInputType()
    {
        checkOptionsPanelVisibility();
        switchDefaultValueField();
        if($('input_type') &&
            ($('input_type').value=='drop_down'
                || $('input_type').value=='radio'
                || $('input_type').value=='checkbox'
                || $('input_type').value=='notice'
            )
        ){
            if($('is_filterable') && !$('is_filterable').getAttribute('readonly')){
                $('is_filterable').disabled = false;
            }
            if($('is_filterable_in_search') && !$('is_filterable_in_search').getAttribute('readonly')){
                $('is_filterable_in_search').disabled = false;
            }
            if($('backend_type') && $('backend_type').options){
                for(var i=0;i<$('backend_type').options.length;i++){
                    if($('backend_type').options[i].value=='int') $('backend_type').selectedIndex = i;
                }
            }
        }
        else {
            if($('is_filterable')){
                $('is_filterable').selectedIndex=0;
                $('is_filterable').disabled = true;
            }
            if($('is_filterable_in_search')){
                $('is_filterable_in_search').disabled = true;
            }
        }

        if ($('input_type') &&
            ($('input_type').value=='drop_down'
            || $('input_type').value=='radio'
            || $('input_type').value=='checkbox'
            || $('input_type').value=='notice'
            )
        ) {
            if ($('used_for_sort_by')) {
                $('used_for_sort_by').disabled = true;
            }
        }
        else {
            if ($('used_for_sort_by') && !$('used_for_sort_by').getAttribute('readonly')) {
                $('used_for_sort_by').disabled = false;
            }
        }

        switchIsFilterable();
    }

    function switchIsFilterable()
    {
        if ($('is_filterable')) {
            if ($('is_filterable').selectedIndex == 0) {
                $('position').disabled = true;
            } else {
                if (!$('position').getAttribute('readonly')){
                    $('position').disabled = false;
                }
            }
        }
    }

    function switchDefaultValueField()
    {
        if (!$('input_type')) {
            return;
        }

        var currentValue = $('input_type').value;

        var defaultValueTextVisibility = false;
        var defaultValueTextareaVisibility = false;
        var defaultValueDateVisibility = false;
        var defaultValueYesnoVisibility = false;
        var scopeVisibility = true;

        switch (currentValue) {
            case 'drop_down':
            case 'radio':
                optionDefaultInputType = 'radio';
                break;

            case 'checkbox':
                optionDefaultInputType = 'checkbox';
                break;

            case 'hidden':
            case 'notice':
                optionDefaultInputType = 'checkbox' ;
                break;
        }

        var elems = document.getElementsByName('is_default[]');

        for (var i = 0; i < elems.length; i++) {
            elems[i].type = optionDefaultInputType;
        }
    }

    function showDefaultRows()
    {
        setRowVisibility('is_required', true);
        setRowVisibility('is_unique', true);
    }

    function setRowVisibility(id, isVisible)
    {
        if ($(id)) {
            var td = $(id).parentNode;
            var tr = $(td.parentNode);

            if (isVisible) {
                tr.show();
            } else {
                tr.blur();
                tr.hide();
            }
        }
    }

    function updateRequriedOptions()
    {
        if ($F('input_type')=='drop-down' && $F('is_required')==1) {
            $('option-count-check').addClassName('required-options-count');
        } else {
            $('option-count-check').removeClassName('required-options-count');
        }
    }

    function saveAttributeInNewSet(promptMessage)
    {
        var newAttributeSetName;

        prompt({
            content: promptMessage,
            actions: {
                confirm: function(val) {
                    newAttributeSetName = val;

                    if (!newAttributeSetName) {
                        return;
                    }

                    var rules = ['required-entry', 'validate-no-html-tags'];
                    for (var i = 0; i < rules.length; i++) {
                        if (!jQuery.validator.methods[rules[i]](newAttributeSetName)) {
                            alert({
                                content: jQuery.validator.messages[rules[i]]
                            });

                            return;
                        }
                    }

                    var newAttributeSetNameInputId = 'new_attribute_set_name';

                    if ($(newAttributeSetNameInputId)) {
                        $(newAttributeSetNameInputId).value = newAttributeSetName;
                    } else {
                        $('edit_form').insert({
                            top: new Element('input', {
                                type: 'hidden',
                                id: newAttributeSetNameInputId,
                                name: 'new_attribute_set_name',
                                value: newAttributeSetName
                            })
                        });
                    }
                    // Temporary solution will replaced after refactoring of attributes functionality
                    jQuery('#edit_form').triggerHandler('save');
                }
            }
        });
    }

    if($('input_type')){
        Event.observe($('input_type'), 'change', updateRequriedOptions);
        Event.observe($('input_type'), 'change', bindAttributeInputType);
    }

    if ($('is_filterable')) {
        Event.observe($('is_filterable'), 'change', switchIsFilterable);
    }

    if ($('is_required')) {
        Event.observe($('is_required'), 'change', updateRequriedOptions);
    }

    jQuery(function($) {
        bindAttributeInputType();
        $('.attribute-popup .collapse, [data-role="advanced_fieldset-content"]')
            .collapsable()
            .collapse('hide');
    });

    window.saveAttributeInNewSet = saveAttributeInNewSet;
    window.updateRequriedOptions = updateRequriedOptions;
    window.setRowVisibility = setRowVisibility;
    window.showDefaultRows = showDefaultRows;
    window.switchDefaultValueField = switchDefaultValueField;
    window.switchIsFilterable = switchIsFilterable;
    window.bindAttributeInputType = bindAttributeInputType;
    window.checkOptionsPanelVisibility = checkOptionsPanelVisibility;
    window.toggleApplyVisibility = toggleApplyVisibility;

});
</script>
