<?php
/** @var \Amasty\InstagramFeed\Block\Widget\Feed\Slider $block */
$posts = $block->getPosts();
$rand = random_int(1, 10000);
$postsIndent = (int)$block->getPadding();
$postSizeNumber = $block->getPostSizeNumber();
$columnsCount = $block->getColumnsCount();
$postsContainerWidth = ($postSizeNumber + $postsIndent * 2) * $columnsCount + 20; // 20px - Slider Indent
?>

<style>
    .aminst-wrapper-<?= (int)$rand ?> .aminst-feed-posts {
        margin: -<?= (int)$postsIndent; ?>px 0;
        max-width: <?= (int)$postsContainerWidth; ?>px;
    }
</style>

<?php if (count($posts)): ?>
    <section class="aminst-feed-slider-container theme-slider-container aminst-feed-wrapper aminst-wrapper-<?= (int)$rand ?>">
        <?php if ($block->getTitle()): ?>
            <h4 class="aminst-feed-title">
                <?= $block->escapeHtml($block->getTitle()) ?>
            </h4>
        <?php endif;?>
        <article class="aminst-feed-posts theme-slider-content"
                 data-aminst-js="post-items"
                 data-mage-init='{"amInstHover":{}}'>

            <?php /** @var \Amasty\InstagramFeed\Api\Data\PostInterface $post */ ?>
            <div class="swiper-container theme-slider swiper-container-instagram" data-mage-init='{"instagramSlider": {
                    "container" : ".aminst-wrapper-<?= (int)$rand ?>"
                }}'>
                <div class="swiper-wrapper">
                    <?php foreach ($posts as $post): ?>
                        <?php $relationLinkHtml = $block->getRelationLinkHtml($post) ?>
                        <figure class="swiper-slide aminst-feed-post
                        -<?= $block->escapeHtml($block->getPostSize()) ?>"
                                data-aminst-js="post-item"
                            <?php if ($relationLinkHtml): ?>
                                data-aminst-hover="true"
                            <?php endif; ?>>
                            <?php $caption = $post->getCaption() ?>

                            <a class="aminst-feed-link -<?= /* @noEscape */ $block->isShowDescription() ? 'en-desc' : 'dis-desc' ?>"
                               href="<?= $block->escapeUrl($post->getPermalink()) ?>"
                               target="_blank"
                               data-aminst-js="feed-link"
                                <?php if ($block->isShowDescription()): ?>
                                    title="<?= $block->escapeHtml($caption) ?>"
                                <?php endif; ?>

                            >
                                <img class="aminst-feed-img swiper-lazy"
                                     src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_LazyLoad::images/pixel.jpg')) ?>"
                                     data-src="<?= $block->escapeUrl($post->getMediaUrl()) ?>"
                                     alt="<?= $block->escapeHtml(__('Instagram Image')) ?>"
                                     width="275"
                                     height="275"
                                />
                                <div class="swiper-lazy-preloader"></div>

                                <?php if ($block->isShowDescription()): ?>
                                    <figurecaption class="aminst-feed-comment-cont">
                                        <p class="aminst-feed-review">
                                            <span class="aminst-feed-likes"><?= $block->escapeHtml($post->getLikeCount()) ?></span>
                                            <span class="aminst-feed-comments"><?= $block->escapeHtml($post->getCommentsCount()) ?></span>
                                        </p>
                                        <p class="aminst-feed-caption"><?= $block->escapeHtml($caption) ?></p>
                                    </figurecaption>
                                <?php endif; ?>
                            </a>
                            <?= /* @noEscape */ $relationLinkHtml ?>
                        </figure>
                    <?php endforeach; ?>
                </div>
            </div>
            <div class="swiper-button-next">
                <i class="fal fa-long-arrow-right"></i>
            </div>
            <div class="swiper-button-prev">
                <i class="fal fa-long-arrow-left"></i>
            </div>
        </article>
    </section>
    <?php if ($block->isPopupEnabled()): ?>
        <script type="text/x-magento-init">
            {
                ".aminst-wrapper-<?= (int)$rand ?> [data-aminst-js='post-item']": {
                    "Amasty_InstagramFeed/js/post/popup": {
                        "loaderUrl" : "<?= $block->escapeUrl($block->getPopupUrl()) ?>"
                    }
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>
