<section class="admin__page-section smartblinds-api-tab-content">
    <div class="admin__page-section-title">
        <span class="title">Smartblinds API</span>
    </div>
    <div class="admin__page-section-item">
        <div class="admin__page-section-item-title">
            <span class="title"><?= __('Error') ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <pre lang="xml" style="white-space: pre-line;">
            <?php
            echo $block->getBeatyErrror();
            ?>
                </pre>
        </div>
    </div>
</section>
