<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <?php $transparency = $_item->getProduct()->getResource()->getAttribute('transparency')->getFrontend()->getValue($_item->getProduct()); ?>
        <?php if($transparency): ?>
        <p class="sku"><?= $block->escapeHtml($transparency) ?></p>
        <?php endif; ?>
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options">
                <dt><strong><em>De doek</em></strong></dt>
                <dd>
                    <?=$block->escapeHtml($_item->getProduct()->getSku());?>  <?= /* @noEscape */  nl2br($block->escapeHtml($_item->getColor())) ?>
                </dd>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= (float) $_item->getQtyOrdered() ?></td>
</tr>
