<?php /** @var Magento\Catalog\Block\Product\View $block */ ?>
<?php if ($block->getProduct()->getSku() == 'curtain_tracks'): ?>
<div class="product-info-messages">
    <div class="discount-message" data-role="product-info-discount-message">
        <?= $block->escapeHtml($block->getData('discount_message')) ?>
    </div>
    <div class="delivery-message">
        <?= $block->escapeHtml($block->getProduct()->getData('delivery_terms')) ?>
    </div>
    <div class="measurement-message">
        <?= $block->escapeHtml($block->getData('measurement_message')) ?>
    </div>
</div>
<?php endif; ?>
