<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product = $block->getProduct();
$isConfigurable = $_product->getTypeId() === 'configurable';
$displayNoneStyle = $isConfigurable ? ' style="display:none"' : '';
?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart update" data-role="box-tocart-bottom" <?= $displayNoneStyle ?>>
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
            <div class="field qty" data-role="addtocart-qty">
                <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                <div class="control">
                    <span class="qty-btn decrease-qty"><i class="fal fa-minus"></i></span>
                    <input type="number"
                           name="qty"
                           id="qty"
                           min="0"
                           value=""
                           title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                    <span class="qty-btn increase-qty"><i class="fal fa-plus"></i></span>
                </div>
            </div>
            <?php endif; ?>
            <div class="product-info-price">
                <?= $block->getChildHtml('product.price.final.additional') ?>
            </div>
            <div class="actions">
                <div class="actions">
                    <button type="submit"
                            title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                            class="action primary tocart a2"
                            id="product-addtocart-button" disabled <?= $displayNoneStyle ?>>
                        <span><?= $block->escapeHtml($buttonTitle) ?></span>
                    </button>
                </div>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/js/validate-product": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
    <script type="text/javascript">
        require([
            'jquery'
        ],function($) {
            var $input = $('[data-role=box-tocart-bottom] .input-text.qty'),
                $button = $('[data-role=box-tocart-bottom] .qty-btn');

            $button.on('click', function(){
                var qty = parseInt($input.val());

                if ($(this).hasClass('decrease-qty') && qty > 1) {
                    qty--;
                    $input.val(qty);
                }
                if ($(this).hasClass('increase-qty')) {
                    qty++;
                    $input.val(qty);
                }
            });
        });
    </script>
<?php endif; ?>
