<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<style>
    .mflazyzoad-no-js [data-original],
    .mflazyzoad-no-js [data-originalset] {
        display: none!important;
    }
</style>
<script data-rocketjavascript="false">
    document.body.className = document.body.className.replace('mflazyzoad-no-js', '');
    require(['Magefan_LazyLoad/js/lazyload.min'], function () {
        var lazyLoadConfig = <?= $block->getLazyLoadConfig() ?>;
        if (document.readyState !== 'loading') {
            var myLazyLoad = new LazyLoad(lazyLoadConfig);
            setTimeout(function(){
                new LazyLoad(lazyLoadConfig);
            }, 2000);
        } else {
            document.addEventListener("DOMContentLoaded", function() {
                var myLazyLoad = new LazyLoad(lazyLoadConfig);
                setTimeout(function(){
                    new LazyLoad(lazyLoadConfig);
                }, 2000);
            });
        }
    });
</script>
<script>
    require(['jquery', 'domReady!'], function($){

        function replacePixelImage() {
            var $t = $(this);
            if (!$t.hasClass(l)) {
                var src = $t.data('original');
                if (src) {
                    $t.attr('src', src).addClass(l);
                }
                var srcset = $t.data('originalset');
                if (srcset) {
                    $t.attr('srcset', srcset).addClass(l);
                }
            }
        }

        /* Fix for product tabs */
        var l = 'loaded';
        $('.product.info.detailed .data.item.title a').click(function(){
            $('.product.info.detailed img[data-original^="h"],.product.info.detailed source[data-originalset^="h"]').each(replacePixelImage);
        });
        $('.nav-sections .navigation').on('click mouseenter', function(){
            $(this).find('img[data-original^="h"],source[data-originalset^="h"]').each(replacePixelImage);
        });
        $('.width-height-option .pdp-options-save-button [data-role="progress-button"]:not(.progress-btn)').on('click', function(){
            $('.swatch-option.image img[data-original^="h"]').each(replacePixelImage);
        });

        /* Fix for sliders */
        var intr = setInterval(function(){
            $sliders = $('.slick-track, .swiper-wrapper, .owl-carousel');
            if (!$sliders.length) clearInterval(intr);
            $sliders.each(function() {
                var $imgs = $(this).find('img,source');
                var c = 0;
                $imgs.each(function(){
                    var $img = $(this);
                    if (($img.attr('src') && $img.attr('src').indexOf('pixel.jpg') != -1)
                        || ($img.attr('srcset') && $img.attr('srcset').indexOf('pixel.jpg') != -1)
                    ) {
                        c++;
                    }
                });
                if (c && $imgs.length != c) {
                    $imgs.each(function(){
                        var $img = $(this);
                        var src = $img.data('original');
                        if (src) {
                            $img.attr('src', src);
                        }

                        var srcset = $img.data('originalset');
                        if (srcset) {
                            $img.attr('srcset', srcset).addClass(l);
                        }
                    });
                }
            });
        }, 2000);
    });
</script>
