<?php
/** @var $block \Smartblinds\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$discountHelper = $this->helper(GoMage\CatalogDiscountLabels\Helper\Data::class);
$productAttribute = $this->helper(Smartblinds\Checkout\Helper\ProductAttribute::class);
$chItems = $_item->getChildren();
foreach ($chItems as $item) {
    if ($_item->getSku() == $item->getSku()) {
        $product = $item->getProduct();
    }
}
/** @var \Smartblinds\Checkout\Helper\CartItem $cartItemHelper */
$cartItemHelper = $this->helper(\Smartblinds\Checkout\Helper\CartItem::class);
?>
<div class="cart item">
    <div class="item-info">
        <div class="item-info-image">
            <?php $discountPercent = $this->helper(\Smartblinds\Catalog\Helper\Data::class)->getDiscountPercent($product); ?>
            <?php if ($discountPercent): ?>
                <div class="discount-badge">
                    <span>
                        <?= $discountPercent ?>
                    </span>
                </div>
            <?php endif; ?>
            <?php if ($block->hasProductUrl()) : ?>
            <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
               title="<?= $block->escapeHtml($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo">
                <?php else : ?>
                <span class="product-item-photo">
                <?php endif; ?>
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                <?php if ($block->hasProductUrl()) : ?>
            </a>
        <?php else : ?>
            </span>
        <?php endif; ?>
        </div>
        <div class="item-info-content">
            <div class="product-item-details">
                <?php if ($label = $discountHelper->displayDiscountLabel($product)): ?>
                    <div class="cart-discount-info"><?= __('Tijdelijk %1 korting', $label); ?></div>
                <?php endif; ?>
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) : ?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else : ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()) : ?>
                    <dl class="item-options">
                        <?php
                        $systemTypeAttr = $productAttribute->getAttribute('system_type');

                        $systemTypeAttrId = null;
                        $isShowMotorSide = true;
                        if (!empty($systemTypeAttr)) {
                            $systemTypeAttrId = $systemTypeAttr->getId();
                            foreach ($_options as $_option) {
                                if($_option['option_id'] == $systemTypeAttrId && strtolower($_option['value']) === 'tdbu'){
                                    $isShowMotorSide = false;
                                    break;
                                }
                            }
                        }

                        $controlTypeAttr = $productAttribute->getAttribute('control_type');

                        $controlTypeAttrId = null;
                        if (!empty($controlTypeAttr)) {
                            $controlTypeAttrId = $controlTypeAttr->getId();
                        }

                        $motorSideOptId = null;
                        $productOptions = $_item->getProduct()->getOptions();
                        if(is_array($productOptions)){
                            foreach ($productOptions as $option) {
                                if($option->getOptionCode() === 'motor_side'){
                                    $motorSideOptId = $option->getOptionId();
                                }
                            }
                        }
                        ?>
                        <?php foreach ($_options as $_option) : ?>
                            <?php if($isShowMotorSide === false && $motorSideOptId == $_option['option_id']){continue;} ?>
                            <?php if ((int)$controlTypeAttrId !== (int)$_option['option_id'] || $productAttribute->isChainCustomerGroup()) : ?>
                                <?php
                                try {
                                    $optValue = json_decode($_option['value']);
                                    $optText = [];
                                    foreach ($optValue as $optKey => $optItem) {
                                        $optText[] = __($optKey) . ": " . ((float)$optItem / 10);
                                    }
                                    $_option['value'] = implode(", ", $optText);
                                } catch (\Exception|\Error $e) {

                                }
                                ?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                <dd>
                                    <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                        <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                    <?php else : ?>
                                        <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                    <?php endif; ?>
                                </dd>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </dl>
                <?php endif; ?>
                <?php if ($_deliveryTerms = $_item->getDeliveryTerms()) : ?>
                    <div class="delivery-message"><?= $_deliveryTerms ?></div>
                <?php endif; ?>
                <?php if ($messages = $block->getMessages()) : ?>
                    <?php foreach ($messages as $message) : ?>
                        <div class="cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) : ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif; ?>
            </div>
            <div class="cart-group-price-qty">
                <div class="qty">
                    <div class="field qty">
                        <div class="control qty">
                            <button class="qty-btn decrease-qty"><i class="fal fa-minus"></i></button>
                            <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                                <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                                       name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                       data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                       value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                       type="number"
                                       size="4"
                                       step="any"
                                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                       class="input-text qty"
                                       data-validate="{required:true,'validate-greater-than-zero':true}"
                                       data-role="cart-item-qty"/>
                            </label>
                            <button class="qty-btn increase-qty"><i class="fal fa-plus"></i></button>
                        </div>
                    </div>
                </div>
                <?php $addInfoBlock2 = $this->getLayout()->getBlock('additional.product.info.second'); ?>
                <?php if ($addInfoBlock2) : ?>
                    <?= $addInfoBlock2->setItem($_item)->toHtml() ?>
                <?php endif; ?>
                <div class="cart-item-price-block">
                    <?php if ($canApplyMsrp) : ?>
                        <div class="col msrp">
                        <span class="pricing msrp">
                            <span
                                class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                            <a href="#" class="action help map"
                               id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                               data-mage-init='{"addToCart":{
                                                    "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                                    "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                                    "showAddToCart": false
                                                    }
                                                }'
                            >
                                <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                            </a>
                        </span>
                        </div>
                    <?php else : ?>
                        <?php if ($cartItemHelper->needShowOriginalPrice($_item)): ?>
                            <div class="old-price"
                                <?= $cartItemHelper->getOriginalUnitPriceHtml($_item) ?>
                            </div>
                        <?php endif; ?>
                        <div class="price"
                            <?= $block->getUnitPriceHtml($_item) ?>
                        </div>
                    <?php endif; ?>
                <!-- TODO -->
                <!--<div class="subtotal">
                        <?php if ($canApplyMsrp) : ?>
                            <span class="cart msrp subtotal">--</span>
                        <?php else : ?>
                            <?= $block->getRowTotalHtml($_item) ?>
                        <?php endif; ?>
                    </div>-->

            </div>
        </div>

        <div class="item-actions">
            <div class="actions-toolbar">
                <?= /* @noEscape */
                $block->getActions($_item) ?>
            </div>
        </div>
    </div>
</div>
</div>
