<?php
/** @var \MageWorx\OptionFeatures\Block\Features $block */
?>
<script type="text/x-magento-init">
   {
       "*": {
            "MageWorx_OptionFeatures/js/features-init": {
                "jsonData": <?= /* @noEscape */ $block->getJsonData();?>,
                "defaultJsonData": <?= /* @noEscape */ $block->getIsDefaultJsonData();?>
            },
            "selectionLimitValidationRule": {
                "config": <?= /* @noEscape */ $block->getSelectionLimitJsonData();?>
            }
       }
   }
</script>
