<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<div class="home-navigation-wrap">
    <div class="home-navigation">
        <ul>
            <?= /* @noEscape */ $_menuHtml?>
            <?= $block->getChildHtml() ?>
        </ul>
    </div>
</div>
