<?php
/**
 * Mageplaza
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Mageplaza.com license that is
 * available through the world-wide-web at this URL:
 * https://www.mageplaza.com/LICENSE.txt
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this extension to newer
 * version in the future.
 *
 * @category    Mageplaza
 * @package     Mageplaza_SpecialPromotions
 * @copyright   Copyright (c) Mageplaza (http://www.mageplaza.com/)
 * @license     https://www.mageplaza.com/LICENSE.txt
 */

namespace Mageplaza\SpecialPromotions\Model\Rule\Action\Discount;

use Magento\Framework\Pricing\PriceCurrencyInterface;
use Magento\SalesRule\Model\Rule;
use Magento\SalesRule\Model\Rule\Action\Discount\DataFactory;
use Magento\SalesRule\Model\Validator;
use Mageplaza\SpecialPromotions\Helper\Data;

/**
 * Class ToFixed
 * @package Mageplaza\SpecialPromotions\Model\Rule\Action\Discount
 */
class ToFixed extends Rule\Action\Discount\ToFixed
{
    /**
     * @var Data
     */
    protected $helper;

    /**
     * ToFixed constructor.
     *
     * @param Validator $validator
     * @param DataFactory $discountDataFactory
     * @param PriceCurrencyInterface $priceCurrency
     * @param Data $helper
     */
    public function __construct(
        Validator $validator,
        DataFactory $discountDataFactory,
        PriceCurrencyInterface $priceCurrency,
        Data $helper
    ) {
        $this->helper = $helper;

        parent::__construct($validator, $discountDataFactory, $priceCurrency);
    }

    /**
     * @inheritDoc
     */
    public function calculate($rule, $item, $qty)
    {
        if (!$this->helper->isEnabled($item->getStoreId())) {
            /** @var Rule\Action\Discount\Data $discountData */
            $discountData = $this->discountFactory->create();

            $discountData->setAmount(0);
            $discountData->setBaseAmount(0);

            return $discountData;
        }

        if ($this->helper->versionCompare('2.4.3')) {
            $store       = $item->getQuote()->getStore();
            $itemPrice   = $this->validator->getItemPrice($item);
            $quoteAmount = $this->priceCurrency->convert($rule->getDiscountAmount(), $store);

            if ($quoteAmount > $itemPrice) {
                $rule->setDiscountAmount($itemPrice);
            }
        }

        return parent::calculate($rule, $item, $qty); // TODO: Change the autogenerated stub
    }

    /**
     * @param float $qty
     * @param Rule $rule
     *
     * @return float
     */
    public function fixQuantity($qty, $rule)
    {
        $step = $rule->getDiscountStep();
        if ($step) {
            $qty = floor($qty / $step) * $step;
        }

        return $qty;
    }
}
