<?php

use Magento\Framework\App\Action\Action;

/**
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$_productCollection = $block->getLoadedProductCollection();

/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
$discountHelper = $this->helper(GoMage\CatalogDiscountLabels\Helper\Data::class);
/** @var \GoMage\Samples\ViewModel\Product $viewModel */
$viewModel = $block->getData('view_model');

?>
<?= $block->getChildHtml('category.products.list.actions') ?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_list';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?> samples-products-wrapper">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item 1"
                    data-role="sample_to_basket_id_<?= $_product->getId() ?>"
                    data-bind="scope: 'sample_to_basket_id_<?= $_product->getId() ?>'">
                    <div class="product-item-info"
                         data-bind="css: toggleClass"
                         id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                         data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = 'left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;';
                        }
                        ?>
                        <div class="action-wrapper">
                            <span class="smpl-btn-add" data-bind="click: addToBasket"></span>
                            <span class="smpl-btn-remove" data-bind="click: removeFromBasket"></span>
                        </div>
                        <div class="remove remove-smpl" data-bind="click: removeFromBasket">
                            <i class="fad fa-times-circle"></i>
                        </div>
                        <div class="product details product-item-details">
                            <?php if ($label = $discountHelper->displayDiscountLabel($_product)): ?>
                            <div class="discount-badge">
                                <?= $label ?>
                            </div>
                            <?php endif; ?>
                            <?php // Product Image ?>
                            <a href="javascript:void(0)"
                               class="product photo product-item-photo"
                               tabindex="-1">
                                    <?= $block->getImage($_product, 'category_swatch')->toHtml() ?>
                            </a>
                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <strong class="product name product-item-name <?= $_product->getData('saving_energy') ? 'saving-energy-icon' : '';?>">
                                <span class="product-item-link"><?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?></span>
                            </strong>
                            <?php
                            $transparencyIconClass = '';
                            if ($_product->getData('transparency') == 212) {
                                $transparencyIconClass = 'lightfiltering';
                            }
                            if ($_product->getData('transparency') == 213) {
                                $transparencyIconClass = 'blackout';
                            }
                            if ($_product->getData('transparency') == 256) {
                                $transparencyIconClass = 'sheer';
                            }
                            ?>
                            <div class="product-subtitle <?= $transparencyIconClass?>">
                                <?= $_product->getAttributeText('transparency')?: (($_product->getData('system_category') !== 'venetian_blinds') ? __('Two layered') : '') ?>
                            </div>
                            <?= $block->getProductDetailsHtml($_product) ?>
                            <?php if ($_product->getTypeId() === 'simple') : ?>
                                <div class="product-item-price-group">
                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions">
                                            <div class="actions-primary">
                                                <?php if ($_product->isSaleable()):?>
                                                    <!-- ko if: items.length -->
                                                    <button
                                                        type="button"
                                                        data-bind="click: addToBasket"
                                                        class="action tocart secondary add-smpl">
                                                        <span data-bind="text: buttonText">
                                                            <?= $escaper->escapeHtml(__('Select')) ?>
                                                        </span>
                                                    </button>
                                                    <!-- /ko -->
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <script type="text/x-magento-init">
                    {
                        "*": {
                            "Magento_Ui/js/core/app": {
                                "components": {
                                    "sample_to_basket_id_<?= $_product->getId() ?>": {
                                        "component": "GoMage_SamplesCategory/js/view/catalog/product/list/add",
                                        "addToCartClass": "<?= $block->escapeJs($viewModel->getAddToCartClass()) ?>",
                                        "addedToCartClass": "<?= $block->escapeJs($viewModel->getAddedToCartClass()) ?>",
                                        "addButtonText": "<?= $escaper->escapeHtml(__('Select')) ?>",
                                        "addedButtonText": "&#x2714;",
                                        "items": <?= $viewModel->getProductSampleItemsJson($_product) ?>,
                                        "itemId": <?= $block->escapeJs($_product->getId()) ?>,
                                        "elementSelector": "[data-role=sample_to_basket_id_<?= $_product->getId() ?>]"
                                    }
                                }
                            }
                        }
                    }
                    </script>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
<?php endif; ?>
