<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
$configProvider = $block->getData('configProvider');
?>

<div class="block-search-wrap">

    <div class="block block-search">
        <div class="block block-title"><strong><?= $block->escapeHtml(__('Search')) ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form"
                  action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?= $block->escapeHtml(__('Search')) ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                                <?php if ($configProvider->isSuggestionsAllowed()):?>
                                   data-mage-init='{"quickSearch":{
                                        "formSelector":"#search_mini_form",
                                        "url":"<?= $block->escapeUrl($helper->getSuggestUrl())?>",
                                        "destinationSelector":"#search_autocomplete",
                                        "minSearchLength":"<?= $block->escapeHtml($helper->getMinQueryLength()) ?>"}
                                   }'
                                <?php endif;?>
                               type="text"
                               name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                               value=""
                               placeholder="<?= $block->escapeHtmlAttr(__('What are you looking for?')) ?>"
                               class="input-text<?php if ($helper->getEscapedQueryText()): ?> _filled<?php endif; ?>"
                               maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"
                               aria-expanded="false"/>
                        <div class="block-search-clear" data-action="clear-search">
                            <i class="fal fa-times"></i>
                        </div>
                    </div>
                    <div class="search-autocomplete-wrap">
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <div class="search-autocomplete-title"><?= $block->escapeHtml(__('Suggestions')) ?></div>
                        <?= $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                        title="<?= $block->escapeHtml(__('Search')) ?>"
                        class="action search"
                        aria-label="Search"
                    >
                        <i class="far fa-search"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>

</div>
