<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<?php
    $url = $this->getUrl('samples');
    $mobileLabel = __('Request Sample');
    $desktopLabel = __('Request Free Sample');
?>
<div class="sample-block pointer">
    <div class="sample-block-inner">
        <div class="sample-block-content">
            <div class="sample-state"
                 data-hide-add-button="true"></div>
            <div class="sample-add mobile-btn" onclick="location.href='<?= $this->getUrl('samples') ?>'">
                <?= $mobileLabel ?>
            </div>
            <div class="sample-add desktop-btn" onclick="location.href='<?= $this->getUrl('samples') ?>'">
                <?= $desktopLabel ?>
            </div>
        </div>
    </div>
</div>
