<?php /* @var $block \Magento\Framework\View\Element\Template */ ?>

<div style="display:none;" data-role="option_modal_wrong-measurement-tips">
    <?= $block->getChildHtml() ?>
</div>
<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'custom',
            responsive: true,
            title: '<?= __('Smartblinds measurement insurance') ?>',
            modalClass: 'pdp-information-popup',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };
        var optionModalSelector = '[data-role=option_modal_wrong-measurement-tips]',
            optionModalButtonSelector = '[data-option-modal=wrong-measurement-tips]';

        var popup = modal(options, $(optionModalSelector));

        $(optionModalButtonSelector).on('click', function() {
            $(optionModalSelector).modal('openModal');
        });
    });
</script>
