<?php
/**
 * @var \Magento\Sales\Block\Adminhtml\Order\View $block
 */
$order = $block->getOrder();

?>
<?php if ($gclid = $order->getData('gclid')): ?>
    <tr>
        <th><?= /* @noEscape */ __('GCLID') ?></th>
        <td><span><?= $block->escapeHtml($gclid) ?></span></td>
    </tr>
<?php endif; ?>
<?php if ($fbp = $order->getData('fbp')): ?>
    <tr>
        <th><?= /* @noEscape */ __('_fbp') ?></th>
        <td><span style="word-break: break-word"><?= $block->escapeHtml($fbp) ?></span></td>
    </tr>
<?php endif; ?>
<?php if ($fbc = $order->getData('fbc')): ?>
    <tr>
        <th><?= /* @noEscape */ __('_fbc') ?></th>
        <td><span style="word-break: break-word"><?= $block->escapeHtml($fbc) ?></span></td>
    </tr>
<?php endif; ?>
