<?php
/** @var $block \Magento\Catalog\Block\Product\View */
$_product = $block->getProduct();
$isConfigurable = $_product->getTypeId() === 'configurable';
$displayNoneStyle = $isConfigurable ? ' style="display:none"' : '';
?>
<?php $buttonTitle = \Magento\Framework\App\ObjectManager::getInstance()
                    ->get(\Magento\Framework\App\Config\ScopeConfigInterface::class)
                    ->getValue('smartblinds_configurable_product/settings/add_to_cart_text', \Magento\Store\Model\ScopeInterface::SCOPE_STORE) ?: __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart" data-role="box-tocart-bottom" <?= $displayNoneStyle ?>>
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty" data-role="addtocart-qty"<?php if ($isConfigurable): ?> style="display:none;"<?php endif; ?>>
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <span class="qty-btn decrease-qty"><i class="fal fa-minus"></i></span>
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                />
                <span class="qty-btn increase-qty"><i class="fal fa-plus"></i></span>
            </div>
        </div>
        <?php endif; ?>
        <div class="product-info-price">
            <?= $block->getChildHtml('product.price.final.additional') ?>
        </div>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart a2"
                    id="product-addtocart-button" disabled <?= $displayNoneStyle ?>>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <p style="margin-top: 10px; z-index: 50 ">
                <?php
                echo $productText = \Magento\Framework\App\ObjectManager::getInstance()
                    ->get(\Magento\Framework\App\Config\ScopeConfigInterface::class)
                    ->getValue('smartblinds_configurable_product/pages/producttext', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
                ?>
            </p>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>

<script type="text/javascript">
    require([
        'jquery'
    ],function($) {
        var $input = $('[data-role=box-tocart-bottom] .input-text.qty'),
            $button = $('[data-role=box-tocart-bottom] .qty-btn');

            $button.on('click', function(){
                var qty = parseInt($input.val());

                if ($(this).hasClass('decrease-qty') && qty > 1) {
                    qty--;
                    $input.val(qty).trigger('change');
                }
                if ($(this).hasClass('increase-qty')) {
                    qty++;
                    $input.val(qty).trigger('change');
                }
            });
    });
</script>
