<?php

/** @var $block \Magento\Catalog\Block\Product\View\Gallery */

use Magento\ConfigurableProduct\Model\Product\Type\Configurable;

$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

if ($block->getProduct()->getTypeId() == Configurable::TYPE_CODE) {
    $mainImageData = $block->getViewFileUrl('images/loader-1.gif');
}

?><div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
<?= $block->getChildHtml('pdp.discount.block') ?>

    <?php if ($block->getProduct()->getTypeId() != Configurable::TYPE_CODE): ?>
    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
    />
    <?php endif; ?>

    <?= $block->getChildHtml('product.info.sample.media') ?>
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                 "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
<script>
    require(['jquery','domReady!'], function ($) {
        $(function(){
            $('.gallery-placeholder').on('gallery:loaded', function () {
                $('.fotorama__stage').append('<div class="gallery-zoom-button"><?= __('Enlarge') ?></div>');
            });
        })
    });
</script>
